### PR TITLE
Various upgrades

### PR DESCRIPTION
**Pull request by pbarbarant**
Upgrades for the 2024 summer benchopt sprint.

- [x] Added fugw via the fmralign wrapper.
- [x] Now the datasets for alignment/decoding are the same.
- [x] Updated various solver parameters
- [x] Fixed benchopt compatibility issues

### CODE REVIEW

**Review by bthirion — COMMENTED** [review]
LGTM, you can merge if you wish.

**Review by bthirion — APPROVED** [review]
LGTM.

**Review by bthirion — APPROVED** [review]
LGTM.

**Comment by pbarbarant** [comment]
> LGTM.

It remains to create an automatic fetcher for the datasets and fix the ``benchopt install`` part. I will do it in another PR.

**Pull request merged**
